### ISSUE TITLE
intermittent `TypeError: NodeClass is not a constructor`

### ISSUE THREAD

**Issue by verhovsky** [tree-sitter/node-tree-sitter#196]
I sometimes get this error when running my tests which parse this bash code with `tree-sitter-bash` 0.21.0

```sh
curl -X POST http://localhost:28139/ --data "foo='bar'"
```

when I start walking the `namedChildren` in the tree

```ts
  const ast = parser.parse(curlCommand);

  // walking the tree to check for missing nodes
  // ...

  // actually do stuff with the tree
  for (const n of ast.rootNode.namedChildren) {
```

```
TypeError: NodeClass is not a constructor
    at unmarshalNode (/Users/space/code/curlconverter/node_modules/tree-sitter/index.js:783:18)
    at Tree.get (/Users/space/code/curlconverter/node_modules/tree-sitter/index.js:25:14)
    at extractCommandNodes (/Users/space/code/curlconverter/src/shell/tokenizer.ts:582:23)
    at tokenize (/Users/space/code/curlconverter/src/shell/tokenizer.ts:724:24)
    at findCommands (/Users/space/code/curlconverter/src/parse.ts:31:12)
    at parse (/Users/space/code/curlconverter/src/parse.ts:58:24)
    at toPythonWarn (/Users/space/code/curlconverter/src/generators/python/python.ts:1927:20)
    at Object.toPython (/Users/space/code/curlconverter/src/generators/python/python.ts:1933:10)
    at <anonymous> (/Users/space/code/curlconverter/test/test.ts:95:28)
```

This happens about halfway through the test suite (test 1390 of 1725), I've only seen it happen twice so far. Both times were on the first time I ran the tests in a new shell. Running `while true; do npm test; done` doesn't trigger it again.

**Comment by verhovsky** [comment]
Also got saw this error

```
Error: Invalid argument
    at get namedChildren [as namedChildren] (/Users/space/code/curlconverter/node_modules/tree-sitter/index.js:166:39)
    at extractCommandNodes (/Users/space/code/curlconverter/src/shell/tokenizer.ts:580:32)
    at tokenize (/Users/space/code/curlconverter/src/shell/tokenizer.ts:722:24)
    at findCommands (/Users/space/code/curlconverter/src/parse.ts:31:12)
    at parse (/Users/space/code/curlconverter/src/parse.ts:58:24)
    at toClojureWarn (/Users/space/code/curlconverter/src/generators/clojure.ts:515:20)
    at Object.toClojure (/Users/space/code/curlconverter/src/generators/clojure.ts:520:10)
    at <anonymous> (/Users/space/code/curlconverter/test/test.ts:95:28)
```

re-ran the tests without any changes and got the `TypeError: NodeClass is not a constructor` error.

**Comment by verhovsky** [comment]
It's fairly common, it happened in the CI as well

https://github.com/curlconverter/curlconverter/actions/runs/8385221889/job/22963783256?pr=645

**Comment by verhovsky** [comment]
@segevfiner

**Comment by segevfiner** [comment]
It could be... But I'm not really sure what could possibly cause this. Guess some good old fashioned debugging is in order... 😛

**Comment by verhovsky** [comment]
Turns out https://github.com/tree-sitter/node-tree-sitter/pull/190#issuecomment-1964263387 is not related to Jest.

**Comment by segevfiner** [comment]
@verhovsky The bug seems to be that we are holding a weak reference in `cached_nodes_`, yet the finalizer hasn't been called yet, as per Node.js docs:
> Finalizer callbacks may be deferred, leaving a window where the object has been garbage collected (and the weak reference is invalid) but the finalizer hasn't been called yet. When using napi_get_reference_value() on weak references returned by napi_wrap(), you should still handle an empty result.

**Comment by verhovsky** [comment]
Fixed by #197
