### ISSUE TITLE
Uncaught Error: A dynamic link library (DLL) initialization routine failed. 

### ISSUE THREAD

**Issue by moodyloo** [tree-sitter/node-tree-sitter#36]
I'm currently creating a Atom package using react, and I'm trying to use tree-sitter to extract function codes. But when I use var Parser = require('tree-sitter');, i receive the error in the title. here are the full error file(I tried to use electron rebuild but still the same error):

```javascript
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\qi_qi\.atom\packages\atombubble\node_modules\tree-sitter\build\Release\tree_sitter_runtime_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/qi_qi/AppData/Local/atom/app-1.34.0/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\qi_qi\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (C:\Users\qi_qi\AppData\Local\atom\app-1.34.0\resources\app.asar\node_modules\tree-sitter\index.js:3:13)
    at Object.<anonymous> (C:\Users\qi_qi\AppData\Local\atom\app-1.34.0\resources\app.asar\node_modules\tree-sitter\index.js:440:3)
    at Module.get_Module._compile (C:\Users\qi_qi\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:146684)
    at Object.value [as .js] (C:\Users\qi_qi\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/qi_qi/AppData/Local/atom/app-1.34.0/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\qi_qi\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:145974)
    at Bubble.componentDidMount (file:///C:/Users/qi_qi/.atom/packages/atombubble/lib/components/bubble.js:112:20)
    at Mh (C:\Users\qi_qi\.atom\packages\atombubble\node_modules\react-dom\cjs\react-dom.production.min.js:228:492)
    at Jh (C:\Users\qi_qi\.atom\packages\atombubble\node_modules\react-dom\cjs\react-dom.production.min.js:220:383)
    at Kh (C:\Users\qi_qi\.atom\packages\atombubble\node_modules\react-dom\cjs\react-dom.production.min.js:219:144)
    at nh (C:\Users\qi_qi\.atom\packages\atombubble\node_modules\react-dom\cjs\react-dom.production.min.js:216:261)
    at Tf (C:\Users\qi_qi\.atom\packages\atombubble\node_modules\react-dom\cjs\react-dom.production.min.js:214:85)
    at Object.enqueueSetState (C:\Users\qi_qi\.atom\packages\atombubble\node_modules\react-dom\cjs\react-dom.production.min.js:134:228)
    at Main.G.setState (C:\Users\qi_qi\.atom\packages\atombubble\node_modules\react\cjs\react.production.min.js:13:224)
    at Main.addBubble (file:///C:/Users/qi_qi/.atom/packages/atombubble/lib/components/main.js:68:10)
    at AtomBubbleView.addBubble (file:///C:/Users/qi_qi/.atom/packages/atombubble/lib/atombubble-view.js:51:23)
    at Object.extract (file:///C:/Users/qi_qi/.atom/packages/atombubble/lib/atombubble.js:53:27)
    at HTMLElement.atombubbleExtract (file:///C:/Users/qi_qi/.atom/packages/atombubble/lib/atombubble.js:27:42)
    at CommandRegistry.handleCommandEvent (C:\Users\qi_qi\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:350017)
```

**Comment by maxbrunsfeld** [comment]
Hi, Atom includes the `tree-sitter` module already, so you shouldn't need to add it as a dependency of your package.

As for this specific error, it looks like the module was compiled to work with the wrong version of node? Perhaps you built it using `nom install`, which compiles it to work with your current `node`, not Atom? You may need to run `apm rebuild` to recompile the native modules.

**Comment by moodyloo** [comment]
Yeah you are right, I used npm install and made things worse. But for some reason requiring the tree sitter inside the Atom developer tools works, but not in the text editor(It says tree sitter module not found)

**Comment by moodyloo** [comment]
Actually now that I used apm rebuild, Atom gives this error when I used "const Parser = require('tree-sitter')":

![image](https://user-images.githubusercontent.com/32241723/53198708-fa69e300-3614-11e9-93ea-5d6b07ca5e96.png)

**Comment by maxbrunsfeld** [comment]
If you're going to `require("tree-sitter")` in your code, you do need to add it as a dependency. I'm not sure you *need* to require Tree-sitter yourself, as it is already used by Atom to parse the code in your editor; you just need to provide a grammar. See https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/.

In general, I don't think this is an issue with Tree-sitter. If you continue to have trouble using native modules in your Atom package, I would recommend asking for help in the `atom` slack channel or [the Atom discussion forums](https://discuss.atom.io).

Good luck!
