### ISSUE TITLE
Parameter type not assigned for parse in TypeScript.

### ISSUE THREAD

**Issue by Symbolk** [tree-sitter/node-tree-sitter#86]
I am trying to use this lib in TypeScript, with the following code:

```typescript
import * as TreeSitter from 'tree-sitter';
import { Point, SyntaxNode, Tree } from 'tree-sitter';
const JavaScript = require('tree-sitter-javascript')
const treeSitter = new TreeSitter()
treeSitter.setLanguage(JavaScript)
    const sourceLines = [
      'let x = 1;',
      'console.log(x);'
    ];
    const tree = treeSitter.parse((index: any, position: Point) => {
      let line = sourceLines[position.row]
      if (line) {
        return line.slice(position.column)
      }
    })
    console.log(tree.rootNode.toString());

```
However, I am facing the following errors:

```
Argument of type '(index: any, position: Point) => string | undefined' is not assignable to parameter of type 'string | Input | InputReader'.
  Type '(index: any, position: Point) => string | undefined' is not assignable to type 'InputReader'.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
```

I skimmed the issues and found this closed one relevant (https://github.com/tree-sitter/node-tree-sitter/pull/55), any ideas?

**Comment by ahlinc** [comment]
I suppose because you need to return `""` empty string in case of end of the input.

**Comment by Symbolk** [comment]
> I suppose because you need to return `""` the empty string in case of the end of the input.

Yeah, you are right! 
Now I can compile and run it, but got another error:

```
'node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 83. This version of Node.js requires NODE_MODULE_VERSION 87. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`)..
```
I have tried node 14.16.1 and 14.0.0, they are corresponding to version 83, but it seems that there is NO version corresponding to version 87, so I am confused.

**Comment by ahlinc** [comment]
Looks like an issue with your environment and somehow customly compiled nodejs version. Could you provide more info:
- About your operation system / distro.
- Do you have a system node installation by some package manager?
- Where do you get other versions of node executables.
- A full command how you call your script with Node when you got the error.

**Comment by Symbolk** [comment]
> Looks like an issue with your environment and somehow customly compiled nodejs version. Could you provide more info:
> 
> * About your operation system / distro.
> * Do you have a system node installation by some package manager?
> * Where do you get other versions of node executables.
> * A full command how you call your script with Node when you got the error.

1. System: macOS 10.15.6
2. Yes, I manage multiple node versions with NVM, the system version is 14.16.0
3. I install the versions with `nvm install VERSION`
4. I am developing a VSCode extension in typescript, and I'd like to integrate node-tree-sitter into it. When debugging the extension with F5 in VSCode, it reports this error.
![Uploading 2F15A4A7-0A52-45B3-99A5-B5B77C598BC5.png…]()

**Comment by gpetrov** [comment]
You have to compile tree-sitter for the electron version of vs code, not your local node

**Comment by ahlinc** [comment]
@Symbolk https://www.electronjs.org/docs/tutorial/using-native-node-modules

**Comment by Symbolk** [comment]
@gpetrov @ahlinc Thanks for the hint! I am trying to rebuild it, but the following error is reported:

```
⠧ Building module: tree-sitter, Completed: 0gyp info spawn /Users/symbolk/.pyenv/versions/3.7.0/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/symbolk/coding/vscode/somanyconflicts/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/symbolk/coding/vscode/somanyconflicts/node_modules/tree-sitter/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/symbolk/coding/vscode/somanyconflicts/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/symbolk/.electron-gyp/13.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/symbolk/.electron-gyp/13.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/symbolk/coding/vscode/somanyconflicts/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/symbolk/.electron-gyp/13.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/symbolk/coding/vscode/somanyconflicts/node_modules/tree-sitter',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
⠋ Building module: tree-sitter, Completed: 0gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/tree_sitter/vendor/tree-sitter/lib/src/lib.o
⠏ Building module: tree-sitter, Completed: 0  LIBTOOL-STATIC Release/tree_sitter.a
⠴ Building module: tree-sitter, Completed: 0  CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/binding.o
⠏ Building module: tree-sitter, Completed: 0In file included from ../src/binding.cc:1:
In file included from /Users/symbolk/.electron-gyp/13.0.1/include/node/node.h:67:
In file included from /Users/symbolk/.electron-gyp/13.0.1/include/node/v8.h:30:
/Users/symbolk/.electron-gyp/13.0.1/include/node/v8-internal.h:454:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:697:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
⠹ Building module: tree-sitter, Completed: 01 error generated.
make: *** [Release/obj.target/tree_sitter_runtime_binding/src/binding.o] Error 1
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/symbolk/coding/vscode/somanyconflicts/node_modules/tree-sitter'.
Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/Users/symbolk/coding/vscode/somanyconflicts/node_modules/tree-sitter'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/Users/symbolk/coding/vscode/somanyconflicts/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (/Users/symbolk/coding/vscode/somanyconflicts/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/Users/symbolk/coding/vscode/somanyconflicts/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /Users/symbolk/coding/vscode/somanyconflicts/node_modules/electron-rebuild/lib/src/cli.js:146:9
```

VSCode information: 
![image](https://user-images.githubusercontent.com/14107297/120095864-e8177180-c15a-11eb-8243-cdae3cba9fd1.png)

Node version: 14.16.0

**Comment by gpetrov** [comment]
This is a common problem when rebuilding node 14+ modules on new macOS.

They need c++14 compiler.

So just edit bindings.gyp and change:
```
'xcode_settings': {
        'CLANG_CXX_LANGUAGE_STANDARD': 'c++11',
      },
```
To
```
'xcode_settings': {
        'CLANG_CXX_LANGUAGE_STANDARD': 'c++14',
      },
```

**Comment by gpetrov** [comment]
Seems there is also a PR for this:

https://github.com/tree-sitter/node-tree-sitter/pull/83

**Comment by Symbolk** [comment]
> Seems there is also a PR for this:
> 
> #83

Right, I also found several similar issues in other projects.

Now the problem is, since the pr is not merged yet but I am blocked by it, is there any way to rebuild a version and depend it on myself? I guess there should be a way but sorry I am new to node and ts.

**Comment by Symbolk** [comment]
I managed to solve this by manually editing `node_modules/tree-sitter/binding.gyp` and run `./node_modules/.bin/electron-rebuild` to rebuild it to get the correct `node_modules/tree-sitter/build/tree_sitter_runtime_binding.node`.

Cheers!
